### ISSUE TITLE
Various problems

### ISSUE THREAD

**Issue by JekSun97** [MizunagiKB/gd_cubism#106]
I started having new problems with the new version, maybe it's because I'm using 4.2 and not 4.1?
Version used: 0.6.3

1. Models stopped displaying when starting the game in GDCubismUserModel, checked with all examples, viewer.tscn works stably.
![2](https://github.com/user-attachments/assets/bdf802c5-e771-4d47-bd29-e00d1926fc0c)

3. Error in demo_transparent.tscn example
Error output: Invalid get index 'ArtMesh121' (on base: 'Dictionary').
![1](https://github.com/user-attachments/assets/6bc0e9ed-5943-40d1-8ca5-4816393065ae)

I would also like to know which model is better to use to view examples? Some parameters are not in the models

**Comment by MizunagiKB** [comment]
The description is insufficient, but demo_transparent.tscn is a code specifically designed for **Nijiiro Mao**, published by Live2D Inc.

It will not function correctly with other Live2D models due to differences in the stored data.

You can obtain Nijiiro Mao from the following location for verification: https://www.live2d.com/en/learn/sample/

**Comment by JekSun97** [comment]
@MizunagiKB  It's clear about the second error. And what about the first one, not a single model is displayed when I load it via GDCubismUserModel in the editor, when I launch the model is not displayed, which did not happen in version 0.6, I checked this on all examples.

1. Launch any example, for example demo_simple.tscn
2. Select the GDCubismUserModel node and load any model in the inspector using the Assets parameter
3. The model is visible in the inspector, but when I launch the scene, the model is not displayed

**Comment by JekSun97** [comment]
@MizunagiKB  Sorry, I forgot to select a texture for the sprite, my mistake.
