### ISSUE TITLE
瞬きと目線追従の方法について

### ISSUE THREAD

**Issue by creeper-0910** [MizunagiKB/gd_cubism#17]
こんにちは。
自分でパーツ分けしたモデルとgodot4.1を使用し、モデルの瞬きと目線追従を行いたいと考えています。
しかし、GDCubismEffectEyeBlinkを追加しても瞬きが再生されません。(モデルの読み込みと、待機モーションの再生は正常です)
そして、目線追従について調べましたがAPI一覧には無いように見受けられます。お時間ありましたら実装をお願いいたします。

**Comment by MizunagiKB** [comment]
@creeper-0910 

## Live2Dモデルの瞬きについて

自作されたLive2Dモデルが瞬きしてくれないとの事ですね。
せっかく作られたモデルがちゃんと動いてくれない理由は、 _GDCubism_ の完成度がまだまだ低いというのが大いにありそうです。

_GDCubism_ は _CubismNativeFramework_ に依存している部分がかなりあるまして、瞬きの設定は固定となっています。
ここでいう固定というのは、以下のリンク先にあるオフィシャルドキュメントに記載されている方法で作られた構造のみをサポートしているという意味となります。

https://docs.live2d.com/cubism-editor-manual/eye-blink-settings/

### 構造の確認方法について

もし作成された .model3.json の中を確認出来るのでしたら、以下の様な項目が含まれているかを確認してみてもらえますでしょうか。

![fig1](https://github.com/MizunagiKB/gd_cubism/assets/5047878/83b59c0a-651d-4638-9c09-10dbb5636825)

上記画像ですと、`"Groups"` という中に `"Name": "EyeBlink"` （青枠の部分）が含まれている状態となります。


### Godot Engine の Editor 上で確認する方法について

実際の Editor 上で確認する方法としては以下の方法があります。

![fig2](https://github.com/MizunagiKB/gd_cubism/assets/5047878/ca1c84f5-b68b-483a-a3f6-fa6da96b421d)

1. Godot Engine の Editor 上で、 _GDCubismUserModel_ の Inspector を開きます。このとき _GDCubismEffectEyeBlink_ や _GDCubismEffectBreath_ がぶら下がっている場合は一旦削除するか、それぞれの Inspector から Active を Off にしてください。
2. Parameter Mode（青枠の部分）を _NoneParameter_ （内部でパラメータが設定されないようにするモード）に変更します。
3. この状態で Param Eye L Open と Param Eye R Open （赤枠の部分）を操作してみてください。
4. 正しく設定されていれば、 0.0 で目が閉じて 1.0 で目が開いている状態になります。

> Param Eye L Open, Param Eye R Open という名称は作成されたモデルや Cubism Editor のバージョンで異なるかもしれません。

正常に動く様でしたら、 Parameter Mode は _NoneParameter_ のまま、再び _GDCubismEffectEyeBlink_ をぶら下げて（ Off にしていた場合は On にして）ください。その状態で瞬きがされますでしょうか。

もしされる様でしたら、最後に Parameter Mode を _NoneParameter_ から _FullParameter_ に戻してください。 _FullParameter_ の状態で瞬きをしない場合は、作成されたモデルのパラメータの中に瞬きのパラメータと干渉しているものが含まれている可能性があります。

その場合はお手間を取らせることになりますが、Live2D社が公開しているサンプルデータと作成されたデータとを見比べてみて差異があるかを確認してみてもらえますでしょうか。


## 目線追従について

目線追従というのは、恐らくマウスドラッグした際にLive2Dモデルがその方向に視線や首を向ける挙動の事かと思います。
こちらはLive2Dのアプリで見かけるものですし、機能自体 _GDCubism_ が依存している _CubismNativeFramework_ に実装されている機能となります。

それでは、なぜわざわざ存在している機能を削っているのかというと、表示方法を Godot Engine 向けに変更しているために、そのままでは期待するマウス操作にならないためです。
> すこし詳しく記載すると、 _GDCubism_ は _SubViewport_ という別の画面に描画して完成したデータを渡す仕組みとなっており、マウスの情報を扱うには少し工夫が必要になります。

Live2Dモデルを作る人にとって、作ったモデルが反応して動いてくれるのは魅力的な機能だと理解しています。
とはいえ、自分の空き時間に作業しているものですので気長にお待ちください。

**Comment by creeper-0910** [comment]
わかりました、確認します！
お忙しい中godotでlive2dモデルを動かせるようにして頂いて、本当にありがとうございます!🙏

**Comment by MizunagiKB** [comment]
@creeper-0910 

まだコミットしていませんが、以下の挙動を試してみました。
> マウス位置の変換式が必要なので、使用する場合は若干のGDScriptが必要になります。

https://github.com/MizunagiKB/gd_cubism/assets/5047878/6e80742b-78d9-4282-a57a-a6044b65a9b3

**Comment by MizunagiKB** [comment]
v0.3.0 ブランチにAPIとドキュメントの追加を行いました。

https://github.com/MizunagiKB/gd_cubism/tree/0.3

動かすには若干コードを書く必要があります。
デモにある _demo_effect_custom_03.tscn_ を参考にしてみてください。

**Comment by creeper-0910** [comment]
こんなに早く...本当にありがとうございます!
試してみます...!

**Comment by creeper-0910** [comment]
遅くなってしまい申し訳ございません。
まばたきと目線追従、正常に動作しました。ありがとうございます！
追加の質問で申し訳ないのですが、目線追従の際に当方のモデルでは髪の毛の物理演算が目線より先にマウスに追従し揺れてしまい、違和感が発生してしまいます。
設定等で解決するものでしょうか...?

**Comment by MizunagiKB** [comment]
@creeper-0910 

髪が影響を受けるのはプログラムではなくデータの作り方に問題がある様な気がします。

私は Live2D デザイナーではありませんので方法論や作法はわかりませんが、まずどのパラメータが髪に影響を与えているかを特定するのが良いでしょう。
一番良いのはエディタで確認することですが Godot Engine のエディタ上で調査をしたり、手直しができるかもしれません。

Godot Engine のエディタにあるノードツリーで GDCubismEffectTargetPoint を選択した時に表示される Inspector には、 Head, Body, Eyes という項目があります。
これはマウスの動きに合わせてどのパラメータを動かすかのパラメータとなります。

Xがマウスの横移動、Yがマウスの縦移動に反応するのですが、ZはXとYから生成した擬似的な情報となります。
> これは私が考えたわけではなく LIve2D のライブラリがそうなってます。

この値が悪影響を与えている可能性がある場合は Head Angle Z を空白にすることでマウスへの反応を無効化出来ます。

また標準ではないパラメータの場合でしたら、Head Range, Body Range, Eyes Range に 0 を設定してから、どれか一箇所だけを戻して確認すると、どのパラメータが髪に影響をあたえているかが調べられるかもしれません。

影響を絵耐えている原因がわかれば、 Live2Dモデルのデータを修正することで解決できるかもしれません。

あるいは現在の値よりも小さな値を入れる事で、目立たなくする方法も考えられます。

例えば「Eyes Range は 1」「 Body Range は 0」にして、 Head Range を小さな値を設定します。
値が小さいほど動きが限定的になるので、結果的に気にならなくなるかもしれません。

**Comment by creeper-0910** [comment]
どうやらBody Rangeの影響で髪の毛が暴走していたようです。
素早い対応、本当にありがとうございます！
現時点の問題は解決したため、issueをクローズさせていただきます。
