### ISSUE TITLE
日本語がファイル名に使用されている場合、正常に読み込まれない

### ISSUE THREAD

**Issue by creeper-0910** [MizunagiKB/gd_cubism#30]
昨日のPRから(https://github.com/MizunagiKB/gd_cubism/pull/29)
日本語がファイル名に使用されている場合、正常に読み込まれずプレビュー画面にも表示されません。
エラーは以下のとおりです。(全てのファイル名は「もでる.<拡張子>」に統一されています)
![image](https://github.com/MizunagiKB/gd_cubism/assets/56744841/056c6e1b-c207-4812-9053-b22db098be8b)

**Comment by MizunagiKB** [comment]
@creeper-0910

この不具合は、文字の取り扱いが異なる環境間において _GDCubism_ が正しく文字列を変換出来ていない事に起因して発生しています。

* _Godot Engine_ が扱う文字型は _String(char32_t *)_
* _CubismSdkForNative_ が扱う文字型は _char_
* _CubismNativeFramework_ が扱う文字型は _csmChar(char)_, _csmString(csmChar *)_ 
* _JSON(JavaScript Object Notation Data Interchange Format)_ が扱う文字コードは _utf-8_

#29 で提示された方法を行うと取り扱いが _ascii_ のみで表現可能な範囲に制限されるため、結果的に正しく取り扱う事が出来ます。
> 例では日本語を挙げていますが、 _ascii_ 範囲外の文字を扱えば全て問題となります。

**解決方法の提案**

前述した様に文字コードの取り扱いが問題となっているため、以下の様なルールで文字列を処理する様にします。

* _Godot Engine_ から _CubismNativeFramework_ に文字列を渡すときは、 _utf-8(char *)_ に変換する。
* _CubismNativeFramework_ から _Godot Engine_ に文字列を渡すときは、 _utf-32(char32_t *)_ に変換する。

具体的なコードで表現すると以下の様なものになります。

```c++
// Godot Engine -> CubismNativeFramework
String from;
Csm::csmString to = Csm::csmString(from.utf8().ptr());

// CubismNativeFramework -> Godot Engine
Csm::csmString from;
String to; to.parse_utf8(from.GetRawString());
```


この不具合対応は https://github.com/MizunagiKB/gd_cubism/pull/35 で行い、https://github.com/MizunagiKB/gd_cubism/tree/0.3 に取り込まれました。


**関連情報**
* https://github.com/godotengine/godot/blob/master/core/string/ustring.h
* https://github.com/godotengine/godot/blob/master/core/string/ustring.cpp
* https://github.com/Live2D/CubismNativeFramework/blob/develop/src/Type/csmString.hpp
* https://github.com/Live2D/CubismNativeFramework/blob/develop/src/Type/csmString.cpp
* https://www.rfc-editor.org/info/rfc8259
* https://www.rfc-editor.org/info/rfc3629

**Comment by creeper-0910** [comment]
了解しました。対応ありがとうございます！
