### ISSUE TITLE
Windows 10 OS Cubism Build Error

### ISSUE THREAD

**Issue by albertkun** [MizunagiKB/gd_cubism#67]
はじめまして！gd_cubismを作ってくれてありがとうございます！だけど、このエラーが哀れってビルド進めない！

```
internal_cubism_renderer_2d.cpp
internal_cubism_renderer.cpp
internal_cubism_user_model.cpp
internal_cubism_renderer_resource.cpp
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
scons: *** [src\gd_cubism_effect.windows.template_debug.x86_64.obj] Error 2
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
scons: *** [src\private\internal_cubism_renderer_2d.windows.template_debug.x86_64.obj] Error 2
scons: *** [src\private\internal_cubism_renderer.windows.template_debug.x86_64.obj] Error 2
src\gd_cubism_motion_entry.hpp(59): error C2248: 'GDCubismMotionQueueEntryHandle::HandleError': cannot access private enum declared in class 'GDCubismMotionQueueEntryHandle'
src\gd_cubism_motion_entry.hpp(30): note: see declaration of 'GDCubismMotionQueueEntryHandle::HandleError'
src\gd_cubism_motion_entry.hpp(26): note: see declaration of 'GDCubismMotionQueueEntryHandle'
scons: *** [src\private\internal_cubism_renderer_resource.windows.template_debug.x86_64.obj] Error 2
scons: *** [src\gd_cubism_user_model.windows.template_debug.x86_64.obj] Error 2
scons: *** [src\private\internal_cubism_user_model.windows.template_debug.x86_64.obj] Error 2
scons: *** [src\register_types.windows.template_debug.x86_64.obj] Error 2
scons: building terminated because of errors.
```
日本語で:
```
src\gd_cubism_motion_entry.hpp(59): エラー C2248: 'GDCubismMotionQueueEntryHandle::HandleError': このクラス内で宣言されたプライベートな列挙型にアクセスできません
src\gd_cubism_motion_entry.hpp(30): メモ: 'GDCubismMotionQueueEntryHandle::HandleError' の宣言を参照してください
src\gd_cubism_motion_entry.hpp(26): メモ: 'GDCubismMotionQueueEntryHandle' の宣言を参照してください
scons: *** [src\gd_cubism_effect.windows.template_debug.x86_64.obj] エラー 2
src\gd_cubism_motion_entry.hpp(59): エラー C2248: 'GDCubismMotionQueueEntryHandle::HandleError': このクラス内で宣言されたプライベートな列挙型にアクセスできません
src\gd_cubism_motion_entry.hpp(30): メモ: 'GDCubismMotionQueueEntryHandle::HandleError' の宣言を参照してください
```
僕が基本的パイソンのプログラマーなので、C++のこと全然分かりません。

ちなみに「thirdparty」のフォルダーの内容はこれです：

![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/5f8c5802-cb14-4762-b9a5-682b034b2669)

追加：日本語がちょっとだけ勉強したけど、ちょっと変な日本語を喋ったらすいません！

**Comment by MizunagiKB** [comment]
@albertkun 
Thank you for reporting the issue.

Upon investigation, I found that the build failure was due to an issue in my source code.

Specifically, the problem occurred because I did not explicitly specify an access modifier within the following source code snippet:

**src/gd_cubism_motion_entry.hpp**

```cpp
class GDCubismMotionQueueEntryHandle : public Resource {
    GDCLASS(GDCubismMotionQueueEntryHandle, Resource)
    friend GDCubismUserModel;

    enum HandleError {
        OK = godot::Error::OK,
        FAILED = godot::Error::FAILED
    };
```

The correct version should be as follows:

```cpp
class GDCubismMotionQueueEntryHandle : public Resource {
    GDCLASS(GDCubismMotionQueueEntryHandle, Resource)
    friend GDCubismUserModel;

public:
    enum HandleError {
        OK = godot::Error::OK,
        FAILED = godot::Error::FAILED
    };
```

I have already fixed this issue, and it is resolved in the latest version, which is **0.5.2**. You can obtain it from the following link:

* [gd_cubism v0.5.2](https://github.com/MizunagiKB/gd_cubism/releases/tag/v0.5.2)

### About C++ Access Modifiers

In C++, access modifiers allow you to specify the visibility level of class members (functions or variables). Here are the three main access modifiers:

- **public**: Members declared as public can be accessed from anywhere. Objects of the class can directly access public members.
- **protected**: Members declared as protected can be accessed within the class itself and by its derived classes.
- **private**: Members declared as private can only be accessed within the class itself. Private members cannot be accessed directly from objects of the class.

In this case, the `HandleError` enum type within the `GDCubismMotionQueueEntryHandle` class was inadvertently set to private due to the missing access modifier. By addressing this issue, we can prevent potential compilation problems for others in the future.

Your report is greatly appreciated. Thank you!

**Comment by MizunagiKB** [comment]
> This is the Japanese version of the English text posted one level above.

不具合の報告ありがとうございます。
調べたところ、ビルドが成功しない原因は私のソースコードに問題がありました。

具体的には、以下のソースコード内においてアクセス修飾子を明示的に指定していないためにコンパイルエラーが発生する環境が生じるというものでした。

**src/gd_cubism_motion_entry.hpp**

```cpp
class GDCubismMotionQueueEntryHandle : public Resource {
    GDCLASS(GDCubismMotionQueueEntryHandle, Resource)
    friend GDCubismUserModel;

    enum HandleError {
        OK = godot::Error::OK,
        FAILED = godot::Error::FAILED
    };
```

正しくは以下のようになります。

```cpp
class GDCubismMotionQueueEntryHandle : public Resource {
    GDCLASS(GDCubismMotionQueueEntryHandle, Resource)
    friend GDCubismUserModel;

public:
    enum HandleError {
        OK = godot::Error::OK,
        FAILED = godot::Error::FAILED
    };
```

こちらは既に修正していますので、最新のバージョンである、0.5.2を取得していただく事で解消致します。

* https://github.com/MizunagiKB/gd_cubism/releases/tag/v0.5.2

### C++のアクセス修飾子について

C++にはアクセス修飾子というのがあり、クラスが保持する関数や変数について公開レベルを指定することが出来るようになっています。

- public: これらのメンバはどこからでもアクセスできます。つまり、クラスのオブジェクトは、そのクラスのpublicメンバに直接アクセスできます。
- protected: これらのメンバは、そのクラス自体と、そのクラスから派生したクラスからアクセスできます。
- private: これらのメンバは、そのクラス自体からのみアクセスできます。つまり、privateメンバはそのクラスのオブジェクトから直接アクセスできません。

今回は GDCubismMotionQueueEntryHandle というクラス内の HandleError という enum 型に対してアクセス修飾子が無指定だったために private となってしまっていました。

私の環境ではmacOSでもWindowsでもビルドが通ってしまうため、この問題に気がつくことが出来ませんでした。
あなたに報告していたいだことで、将来コンパイルできずに困ってしまう方を減らすことが出来ました。

あなたの報告に感謝致します。ありがとう！

**Comment by albertkun** [comment]
僕のバッグレポートが役に立って、よかったです！そして、早めにバッグが見つけて直ってくれてありがとうございます！そして、詳しく説明してありがとう！！英語と日本語の説明がとても便利です！今がビルド成功したなので、確認しました！

![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/4a3560d7-59f1-4f21-a7f2-18023cb4bcf4)

感謝します！！！🙇 🙇 以上の問題なしだから、このレポート閉めます！ 🎆
