### ISSUE TITLE
[質問] プロジェクトがエクスポート時モデルが見つけない

### ISSUE THREAD

**Issue by albertkun** [MizunagiKB/gd_cubism#69]
やったビルドが出来たけど、今日テストプロジェクトが「ウィンドウズ１０」の為にエクスポートしますが、live2dのモデルがない！

これは僕のシーンアレンジです：

![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/398b4d82-5268-4b1a-89f1-9188d9310ba8)

そして、「test.exe」の正面：

![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/77355a70-1342-4b8a-babe-bdcb39afafea)

「.dll」とかちゃんとあると思います。
![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/afd9d41d-c49e-4c14-bae0-5f4747e54e39)

後、僕のエクスポートのオプション：
![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/4f274659-a9b6-498c-87a9-fa94c66af8cd)

申し訳ございませんが、何か手伝ってくれたら感謝します。ありがとうございます。

**Comment by MizunagiKB** [comment]
@albertkun 
This issue pertains to the usage of Godot Engine, not Live2D.

Godot Engine is unable to recognize the usage of indirectly loaded resources (in the case of Live2D, this would include images and JavaScript files loaded by the Live2D library).

Therefore, it is necessary to register the resources you are using, or the folder containing these resources, in the _Resources_ section of the _Export_ settings.

There is a section called **Resource options** in the **Exporting projects** part of the Godot Engine manual.
Please read through it and add your resources accordingly.

https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html#resource-options

----

これはLive2Dではなく、Godot Engineにの使い方に関する問題となります。

Godot Engineは間接的に読み込むリソース（Live2Dの場合はLive2Dのライブラリが読み込む画像やJavaScriptファイル等が該当します）について、利用状況を知ることが出来ません。

そのため、 _Export_ の _Resources_ 欄にあなたが使用しているリソース、或いはリソースが収められているフォルダを登録する必要があります。

Godot Engineのマニュアルの **Exporting projects** に **Resource options** という欄があります。
そこに記述されている説明を読みながら適宜追加してあげてください。

https://docs.godotengine.org/ja/4.x/tutorials/export/exporting_projects.html#resource-options

**Comment by albertkun** [comment]
@MizunagiKB ありがとうございます！！エクスポートオプションはこのフォルダに追加しました：

`addons/gd_cubism/example/res/*`

![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/95c4e529-1ab3-4ba9-8dbd-e9e2fdae607d)

やっとできました！

![image](https://github.com/MizunagiKB/gd_cubism/assets/8574425/2fdcfb7c-c0d2-4983-adfd-d38e9e4d7744)
