### ISSUE TITLE
Godot flies out when I hide the window

### ISSUE THREAD

**Issue by JekSun97** [MizunagiKB/gd_cubism#74]
**Tested versions**
Godot 4.1.3, Godot 4.2.1

**System information**
Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

**Issue description**
When I click the "minimize" button in a running application, godot displays many errors in the console and crashes.
I also created a [bug report](https://github.com/godotengine/godot/issues/89651) on the godot repository, I would be glad if you @MizunagiKB would join the discussion of the problem there if you doubt that the problem is in the plugin.

Errors in Forward+:
![err](https://github.com/MizunagiKB/gd_cubism/assets/130399274/dea7d956-751e-4817-9095-e145bc015eb4)

Errors in Mobile:
![errMobile](https://github.com/MizunagiKB/gd_cubism/assets/130399274/623312a1-5890-400b-abe1-5b2ff5efb133)

**Steps to reproduce**
1. Run my example and run it in Forward+ or Mobile mode
2. Minimize a window
![w](https://github.com/MizunagiKB/gd_cubism/assets/130399274/181e0b2b-8a6e-4c32-9d39-9cfdcaa27efc)
3. Wait about 15 seconds and you will see a huge number of errors

**Minimal reproduction project**
[demoGD.zip](https://github.com/godotengine/godot/files/14639407/demoGD.zip)

**Comment by MizunagiKB** [comment]
I have added a comment to the ongoing discussion at https://github.com/godotengine/godot/issues/89651.

It may be unusual for projects using GodotEngine to heavily utilize SubViewport, but a similar issue existed before.
There might be other hidden issues related to SubViewport.

**Comment by MizunagiKB** [comment]
@JekSun97 Addressing this bug is likely to be challenging and may not be resolved immediately.

As a temporary measure, we have merged the following pull request https://github.com/MizunagiKB/gd_cubism/pull/77 and branch [0.6](https://github.com/MizunagiKB/gd_cubism/tree/0.6
) into this repository.

https://github.com/MizunagiKB/gd_cubism/tree/0.6

In version 0.6, we have made it so that the Live2D model is not rendered when the Window is not displayed.
> If you want to revert this, you can specify it with the scons parameter.

**Comment by JekSun97** [comment]
Good decision! Thank you!
