### ISSUE TITLE
SConsturt line 9

### ISSUE THREAD

**Issue by sdvzxdvxzc** [MizunagiKB/gd_cubism#89]
i was following the build.adoc
when i try scon debug and release ，it happen like this
what part i did wrong?

```
C:\Users\user\Desktop\gd_cubism-main\gd_cubism-main>scons platform=windows arch=x86_64 `target=template_debug`
scons: Reading SConscript files ...

scons: *** missing SConscript file 'godot-cpp\\SConstruct'
File "C:\Users\user\Desktop\gd_cubism-main\gd_cubism-main\SConstruct", line 9, in <module>

C:\Users\user\Desktop\gd_cubism-main\gd_cubism-main>scons platform=windows arch=x86_64 target=template_release
scons: Reading SConscript files ...

scons: *** missing SConscript file 'godot-cpp\\SConstruct'
File "C:\Users\user\Desktop\gd_cubism-main\gd_cubism-main\SConstruct", line 9, in <module>
```

**Comment by MizunagiKB** [comment]
@sdvzxdvxzc 

I will respond to the error in the log you posted as follows:

```
scons: *** missing SConscript file 'godot-cpp\\SConstruct'
File "C:\Users\user\Desktop\gd_cubism-main\gd_cubism-main\SConstruct", line 9, in <module>
```
This error occurs when the _SConstruct_ file cannot be found in the **godot-cpp** folder.

Please check the following:

- Is there a folder named **godot-cpp** in your working directory? (In your case, it would be C:\Users\user\Desktop\gd_cubism-main\gd_cubism-main)
- Is there an SConstruct file inside that folder?

If you cannot find it, it seems that the **godot-cpp** folder could not be obtained due to some malfunction.

> The **godot-cpp** folder refers to another repository using a feature called git submodule. Therefore, if you obtained it from a zip file or just did a git clone, it may not be expanded in its initial state.

- Run `git submodule update --init` in your working directory.
- Use GitHub Desktop to do a git clone.

If you still can't get **godot-cpp**, please try downloading and expanding the contents of the following repository directly:

https://github.com/godotengine/godot-cpp/tree/bc980b59fff6d202150508db3f00c9440022620a

**Comment by sdvzxdvxzc** [comment]
i just download file and put into it
and i do the build again
but i doesnt see there has dll in gd_cubism/bin
![2024-06-06 18 32 40](https://github.com/MizunagiKB/gd_cubism/assets/171753335/a40fe7da-4d30-4900-a586-76c61ee2d34c)

**Comment by MizunagiKB** [comment]
Upon checking the log, it appears that the `MSVC_VERSION` is set to `(undefined)`.
This suggests that either Visual Studio is not installed in your environment, or if it is installed, the C compiler is not being recognized.

As mentioned in the following document, please ensure to include the C/C++ development environment when installing Visual Studio.

https://mizunagikb.github.io/gd_cubism/gd_cubism/0.6/en/build.html#_build_for_windows

**Comment by sdvzxdvxzc** [comment]
thanks🙏
dll debug reslease is done
but cant find node on demo
![2024-06-06 21 28 54](https://github.com/MizunagiKB/gd_cubism/assets/171753335/1648da06-02ea-493e-b698-3228d7622d72)

**Comment by MizunagiKB** [comment]
The extension modules for Godot are typically placed under a folder named `addons`.
GDCubism follows this convention and is placed under the `addons` folder in a folder named `gd_cubism`.

Your project does not currently have an `addons` folder.

For the specific structure, please refer to the structure under the `demo` folder in the repository. If the build has been successful, please first open the `project.godot` within this folder and check its operation.

https://github.com/MizunagiKB/gd_cubism/tree/main/demo

**Comment by sdvzxdvxzc** [comment]
how do i put mao_pro_en into demo
![2024-06-07 13 31 50](https://github.com/MizunagiKB/gd_cubism/assets/171753335/f0410ad8-3ae7-44b8-b9ab-f96fa4a2d6f2)

**Comment by MizunagiKB** [comment]
In the case of the Viewer sample, please deploy the contents to _res://addons/gd_cubism/example/res/live2d_ and place the entire _mao_pro_jp_ folder.

If properly arranged, you will be able to select the Live2D model from the menu.

**Comment by sdvzxdvxzc** [comment]
thanks🙏 the issue is complete

**Comment by MizunagiKB** [comment]
I believe this issue has been resolved, so I will close it. If you have any further concerns, please feel free to create a new issue.

If you need any more assistance, feel free to ask!
